---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.11.3
      hooks:
          - id: ruff
            args: [--fix]
